{
 "title": "Logs Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Api Gateway",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apigateway\", filename=\"/var/log/app/apigateway.log\"}"
    }
   ]
  },
  {
   "title": "Auth Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"auth-service\", filename=\"/var/log/app/auth-service.log\"}"
    }
   ]
  },
  {
   "title": "User Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"user-service\", filename=\"/var/log/app/user-service.log\"}"
    }
   ]
  },
  {
   "title": "Role Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"role-service\", filename=\"/var/log/app/role-service.log\"}"
    }
   ]
  },
  {
   "title": "Cart Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cart-service\", filename=\"/var/log/app/cart-service.log\"}"
    }
   ]
  },
  {
   "title": "Banner Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"banner-service\", filename=\"/var/log/app/banner-service.log\"}"
    }
   ]
  },
  {
   "title": "Category Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"category-service\", filename=\"/var/log/app/category-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-service\", filename=\"/var/log/app/merchant-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Business Serviice",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-business-service\", filename=\"/var/log/app/merchant-business-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Award Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-award-service\", filename=\"/var/log/app/merchant-award-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Detail",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-detail-service\", filename=\"/var/log/app/merchant-detail-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Policy",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-policy-service\", filename=\"/var/log/app/merchant-policy-service.log\"}"
    }
   ]
  },
  {
   "title": "Order Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"order-service\", filename=\"/var/log/app/order-service.log\"}"
    }
   ]
  },
  {
   "title": "Order Item Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"order-item-service\", filename=\"/var/log/app/order-item-service.log\"}"
    }
   ]
  },
  {
   "title": "Product Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"product-service\", filename=\"/var/log/app/product-service.log\"}"
    }
   ]
  },
  {
   "title": "Review Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"review-service\", filename=\"/var/log/app/review-service.log\"}"
    }
   ]
  },
  {
   "title": "Review Detail Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"review-detail-service\", filename=\"/var/log/app/review-detail-service.log\"}"
    }
   ]
  },
  {
   "title": "Shipping Address Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"shipping-address-service\", filename=\"/var/log/app/shipping-address-service.log\"}"
    }
   ]
  },
  {
   "title": "Slider Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"slider-service\", filename=\"/var/log/app/slider-service.log\"}"
    }
   ]
  },
  {
   "title": "Transaction Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"transaction-service\", filename=\"/var/log/app/transaction-service.log\"}"
    }
   ]
  }
 ]
}