server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_ecommerce:3100/loki/api/v1/push

scrape_configs:
  - job_name: apigateway
    static_configs:
      - targets: [localhost]
        labels:
          job: apigateway
          __path__: /var/log/app/apigateway.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: auth-service
    static_configs:
      - targets: [localhost]
        labels:
          job: auth-service
          __path__: /var/log/app/auth-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: email-service
    static_configs:
      - targets: [localhost]
        labels:
          job: email-service
          __path__: /var/log/app/email-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: role-service
    static_configs:
      - targets: [localhost]
        labels:
          job: role-service
          __path__: /var/log/app/role-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: user-service
    static_configs:
      - targets: [localhost]
        labels:
          job: user-service
          __path__: /var/log/app/user-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: category-service
    static_configs:
      - targets: [localhost]
        labels:
          job: category-service
          __path__: /var/log/app/category-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-service
          __path__: /var/log/app/merchant-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: order-item-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-item-service
          __path__: /var/log/app/order-item-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: order-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-service
          __path__: /var/log/app/order-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: product-service
    static_configs:
      - targets: [localhost]
        labels:
          job: product-service
          __path__: /var/log/app/product-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: transaction-service
    static_configs:
      - targets: [localhost]
        labels:
          job: transaction-service
          __path__: /var/log/app/transaction-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: cart-service
    static_configs:
      - targets: [localhost]
        labels:
          job: cart-service
          __path__: /var/log/app/cart-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: review-service
    static_configs:
      - targets: [localhost]
        labels:
          job: review-service
          __path__: /var/log/app/review-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: slider-service
    static_configs:
      - targets: [localhost]
        labels:
          job: slider-service
          __path__: /var/log/app/slider-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: shipping-address-service
    static_configs:
      - targets: [localhost]
        labels:
          job: shipping-address-service
          __path__: /var/log/app/shipping-address-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: banner-service
    static_configs:
      - targets: [localhost]
        labels:
          job: banner-service
          __path__: /var/log/app/banner-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-award-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-award-service
          __path__: /var/log/app/merchant-award-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-business-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-business-service
          __path__: /var/log/app/merchant-business-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-policy-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-policy-service
          __path__: /var/log/app/merchant-policy-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-detail-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-detail-service
          __path__: /var/log/app/merchant-detail-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: review-detail-service
    static_configs:
      - targets: [localhost]
        labels:
          job: review-detail-service
          __path__: /var/log/app/review-detail-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg
