global:
  scrape_interval: 10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          application: 'Otel Collector'
          environment: 'production'
  
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          application: 'Kafka Exporter'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          application: 'Node Exporter'
          environment: 'production'

  - job_name: 'apigateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apigateway:8091']
        labels:
          application: 'API Gateway'
          environment: 'production'

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:8081']
        labels:
          application: 'Auth Service'
          environment: 'production'


  - job_name: 'email-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['email:8080']
        labels:
          application: 'Email Service'
          environment: 'production'

  - job_name: 'role-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['role:8082']
        labels:
          application: 'Role Service'
          environment: 'production'

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user:8083']
        labels:
          application: 'User Service'
          environment: 'production'

  - job_name: 'category-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['category:8084']
        labels:
          application: 'Category Service'
          environment: 'production'

  - job_name: 'merchant-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant:8085']
        labels:
          application: 'Merchant Service'
          environment: 'production'

  - job_name: 'order-item-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-item:8086']
        labels:
          application: 'Order Item Service'
          environment: 'production'

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order:8087']
        labels:
          application: 'Order Service'
          environment: 'production'

  - job_name: 'product-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product:8088']
        labels:
          application: 'Product Service'
          environment: 'production'

  - job_name: 'transaction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transaction:8089']
        labels:
          application: 'Transaction Service'
          environment: 'production'

  - job_name: 'cart-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cart:8090']
        labels:
          application: 'Cart Service'
          environment: 'production'

  - job_name: 'review-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['review:8091']
        labels:
          application: 'Review Service'
          environment: 'production'

  - job_name: 'slider-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['slider:8092']
        labels:
          application: 'Slider Service'
          environment: 'production'

  - job_name: 'shipping-address-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['shipping-address:8093']
        labels:
          application: 'Shipping Address Service'
          environment: 'production'

  - job_name: 'banner-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['banner:8094']
        labels:
          application: 'Banner Service'
          environment: 'production'

  - job_name: 'merchant-award-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant-award:8095']
        labels:
          application: 'Merchant Award Service'
          environment: 'production'

  - job_name: 'merchant-business-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant-business:8096']
        labels:
          application: 'Merchant Business Service'
          environment: 'production'

  - job_name: 'merchant-detail-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant-detail:8097']
        labels:
          application: 'Merchant Detail Service'
          environment: 'production'

  - job_name: 'merchant-policy-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant-policy:8098']
        labels:
          application: 'Merchant Policy Service'
          environment: 'production'

  - job_name: 'review-detail-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['review-detail:8099']
        labels:
          application: 'Review Detail Service'
          environment: 'production'
