apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  APP_ENV: "kubernetes"
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "ECOMMERCE"
  POSTGRES_DB: "ECOMMERCE"
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "30m"
  DB_SEEDER: "true"
  APP_LOGGER: "production"

  KAFKA_BROKERS: "ecommerce-service.svc.cluster.local:9092"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB_AUTH: "0"
  REDIS_DB_ROLE: "1"
  REDIS_DB_USER: "2"
  REDIS_DB_CATEGORY: "3"
  REDIS_DB_MERCHANT: "4"
  REDIS_DB_ORDER_ITEM: "5"
  REDIS_DB_ORDER: "6"
  REDIS_DB_PRODUCT: "7"
  REDIS_DB_TRANSACTION: "8"
  REDIS_DB_CART: "9"
  REDIS_DB_REVIEW: "10"
  REDIS_DB_SLIDER: "11"
  REDIS_DB_SHIPPING_ADDRESS: "12"
  REDIS_DB_BANNER: "13"
  REDIS_DB_MERCHANT_AWARD: "14"
  REDIS_DB_MERCHANT_BUSINESS: "15"
  REDIS_DB_MERCHANT_DETAIL: "16"
  REDIS_DB_MERCHANT_POLICY: "17"
  REDIS_DB_REVIEW_DETAIL: "18"

  OTEL_ENDPOINT: "otel-collector.ecommerce.svc.cluster.local:4317"

  GRPC_AUTH_ADDR: "auth.ecommerce.svc.cluster.local:50051"
  GRPC_ROLE_ADDR: "role.ecommerce.svc.cluster.local:50052"
  GRPC_USER_ADDR: "user.ecommerce.svc.cluster.local:50053"
  GRPC_CATEGORY_ADDR: "category.ecommerce.svc.cluster.local:50054"
  GRPC_MERCHANT_ADDR: "merchant.ecommerce.svc.cluster.local:50055"
  GRPC_ORDER_ITEM_ADDR: "order-item.ecommerce.svc.cluster.local:50056"
  GRPC_ORDER_ADDR: "order.ecommerce.svc.cluster.local:50057"
  GRPC_PRODUCT_ADDR: "product.ecommerce.svc.cluster.local:50058"
  GRPC_TRANSACTION_ADDR: "transaction.ecommerce.svc.cluster.local:50059"
  GRPC_CART_ADDR: "cart.ecommerce.svc.cluster.local:50060"
  GRPC_REVIEW_ADDR: "review.ecommerce.svc.cluster.local:50061"
  GRPC_SLIDER_ADDR: "slider.ecommerce.svc.cluster.local:50062"
  GRPC_SHIPPING_ADDR: "shipping.ecommerce.svc.cluster.local:50063"
  GRPC_BANNER_ADDR: "banner.ecommerce.svc.cluster.local:50064"
  GRPC_MERCHANT_AWARD_ADDR: "merchant-award.ecommerce.svc.cluster.local:50065"
  GRPC_MERCHANT_BUSINESS_ADDR: "merchant-business.ecommerce.svc.cluster.local:50066"
  GRPC_MERCHANT_DETAIL_ADDR: "merchant-detail.ecommerce.svc.cluster.local:50067"
  GRPC_MERCHANT_POLICY_ADDR: "merchant-policy.ecommerce.svc.cluster.local:50068"
  GRPC_REVIEW_DETAIL_ADDR: "review-detail.ecommerce.svc.cluster.local:50069"

  GRPC_AUTH_PORT: "50051"
  GRPC_ROLE_PORT: "50052"
  GRPC_USER_PORT: "50053"
  GRPC_CATEGORY_PORT: "50054"
  GRPC_MERCHANT_PORT: "50055"
  GRPC_ORDER_ITEM_PORT: "50056"
  GRPC_ORDER_PORT: "50057"
  GRPC_PRODUCT_PORT: "50058"
  GRPC_TRANSACTION_PORT: "50059"
  GRPC_CART_PORT: "50060"
  GRPC_REVIEW_PORT: "50061"
  GRPC_SLIDER_PORT: "50062"
  GRPC_SHIPPING_PORT: "50063"
  GRPC_BANNER_PORT: "50064"
  GRPC_MERCHANT_AWARD_PORT: "50065"
  GRPC_MERCHANT_BUSINESS_PORT: "50066"
  GRPC_MERCHANT_DETAIL_PORT: "50067"
  GRPC_MERCHANT_POLICY_PORT: "50068"
  GRPC_REVIEW_DETAIL_PORT: "50069"

  METRIC_EMAIL_ADDR: "8080"
  METRIC_AUTH_ADDR: "8081"
  METRIC_ROLE_ADDR: "8082"
  METRIC_USER_ADDR: "8083"
  METRIC_CATEGORY_ADDR: "8084"
  METRIC_MERCHANT_ADDR: "8085"
  METRIC_ORDER_ITEM_ADDR: "8086"
  METRIC_ORDER_ADDR: "8087"
  METRIC_PRODUCT_ADDR: "8088"
  METRIC_TRANSACTION_ADDR: "8089"
  METRIC_CART_ADDR: "8090"
  METRIC_REVIEW_ADDR: "8091"
  METRIC_SLIDER_ADDR: "8092"
  METRIC_SHIPPING_ADDR: "8093"
  METRIC_BANNER_ADDR: "8094"
  METRIC_MERCHANT_AWARD_ADDR: "8095"
  METRIC_MERCHANT_BUSINESS_ADDR: "8096"
  METRIC_MERCHANT_DETAIL_ADDR: "8097"
  METRIC_MERCHANT_POLICY_ADDR: "8098"
  METRIC_REVIEW_DETAIL_ADDR: "8099"
