apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant_detail
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant_detail
  template:
    metadata:
      labels:
        app: merchant_detail
    spec:
      initContainers:
        - name: init-log-permission
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Setting ownership for /var/log/app"
              chown -R 1000:1000 /var/log/app
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          securityContext:
            runAsUser: 0
      containers:
        - name: merchant_detail
          image: merchant_detail-ecommerce-service:1.0
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8097
            - containerPort: 50067
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8097
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          imagePullPolicy: IfNotPresent
