apiVersion: v1
kind: Service
metadata:
  name: merchant_award
  namespace: ecommerce
spec:
  selector:
    app: merchant_award
  ports:
    - name: http-metrics
      port: 8095
      targetPort: 8095
    - name: grpc
      port: 50065
      targetPort: 50065
  type: ClusterIP
