apiVersion: v1
kind: Service
metadata:
  name: order_item
  namespace: ecommerce
spec:
  selector:
    app: order_item
  ports:
    - name: http-metrics
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 50056
      targetPort: 50056
  type: ClusterIP
