apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ecommerce
spec:
  selector:
    app: product
  ports:
    - name: http-metrics
      port: 8088
      targetPort: 8088
    - name: grpc
      port: 50058
      targetPort: 50058
  type: ClusterIP
